### PR TITLE
update of activator-akka-spray template

### PR DESCRIPTION
**Pull request by antoinell**
includes upgrade of dependencies, and make the web pages be served

### CODE REVIEW

**Comment by janm399** [comment]
This is really great! I've made a few modifications: bumped Scala, Spray and Akka versions; updated the tutorial.

Many thanks for the work!

**Comment by sslavic** [comment]
Some of these changes IMO were wrong, not inline with design described in scaladoc of various types. E.g. Web is no longer Web, Api is no longer Api

**Comment by antoinell** [comment]
Stevo can you elaborate on your comments ? What should be moved where ? Or maybe even better create a pull request allowing the project owner to rectify the code ? 
Regards

**Comment by sslavic** [comment]
BootedCore is not booting Core only, it's booting API/services too, as well as Web. Api and Web traits because of this change, do nothing, yet their scaladoc says differently.

**Comment by antoinell** [comment]
Stevo fair enough.  These are valid points. Maybe create a pull request with a better implementation ? I agree with you that it is important to have code which makes sense and where the name of the classes, their scaladoc, and what the classes actually do is all consistent. I am busy with my day job, my family and other open source projects at the moment.

**Comment by janm399** [comment]
That all makes sense—I'll improve the docs over the holidays

**Comment by sslavic** [comment]
Docs are IMO OK, and follow the design. Some of the changes that came through this pull request are IMO not aligned with the design. As that BootedCore issue I mentioned. Although I have to admit it would be nice that there is a solution in the design for higher level to add stuff to boot sequence, like binding service, and then also higher level APIs to be able to change/override shutdown (to unbind first and only then shutdown the system - but that requires new design, not just cramming stuff into existing design which does not fit there.

For more improvement ideas have a look on practically fork of this project: https://github.com/markglh/Spray-Akka-Json-Error-Handling + issues and pull-requests on this one.

**Pull request merged**
